### PR TITLE
Change maxLinkRate and maxLinkRatePatch types to uint32_t

### PR DESCRIPTION
**Pull request by bavariancake**
The `-igfxmlr` works on its own, but when the `enable-dpcd-max-link-rate-fix` option is set to `01000000`, the method `WIOKit::getOSDataValue()` fails to set `maxLinkRatePatch` unless its data type is `uint32_t`. Compare to e.g. `framebufferPatchEnable`. The same is true for `maxLinkRate`, and changing its data type to `uint32_t` works as well.

Thanks so much for adding the link rate patch to WhateverGreen @0xFireWolf! 👍

### CODE REVIEW

**Comment by 0xFireWolf** [comment]
I think I have explicitly indicated in the manual (a screen shot) that the type of enable-dpcd-max-link-rate-fix should have a Boolean type in the property list file.

Anyway, the code has been merged to the main repo, and I remember that vit9696 has made a minor change to accept any format for those keys. Could you please checkout the latest code and see whether this issue still exists or not?

**Comment by bavariancake** [comment]
Checked latest WhateverGreen master branch - the `enable-dpcd-max-link-rate-fix` option works (it uses getProperty() instead of getOSDataValue() now), but the `dpcd-max-link-rate` is still ignored. The screenshot in the [FAQ](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md) shows type 'Data', like other values.

**Comment by 0xFireWolf** [comment]
I just noticed that Andrey1970AppleLife has changed my screenshot. The original one was at my repo/Manual/img/DPCD-mlr.png.

Would you mind creating a issue at the main repo to see what’s vit9696’s suggestion?

**Comment by bavariancake** [comment]
@0xFireWolf - it looks like the main WhateverGreen repo doesn't allow issues to be created, so I opened a [PR](https://github.com/acidanthera/WhateverGreen/pull/20). I'll close this PR here in the mean time.

**Pull request closed without merging**
